### ISSUE TITLE
Fit zip-code knowledge indicator with RECPI index

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Urban_Indicators#10]
We'll use the indicator developed in
https://www.startupcartography.com/
as an organizing variable for the knowledge data at the zip code level.

We will use patents to organize the skills variables at the city level. 

This still needs #2 to be solved first.

**Comment by RELNO** [comment]
![Screen Shot 2020-04-01 at 10 20 17](https://user-images.githubusercontent.com/14296774/78148078-67e46780-7402-11ea-9ca0-0a8e978f46a9.png)
there's so much knowledge in my house it's about to explode.

**Comment by doorleyr** [comment]
If @RELNO could go outside we'd see the dot following him around.

**Comment by RELNO** [comment]
@doorleyr that's my social distance indicator

**Comment by crisjf** [comment]
I'm almost done with this btw. I just need to organize the code and pickle the model.

**Comment by crisjf** [comment]
Commit 6181bb59b6591e7108578903832f359bcdc80eae solves this.
