### ISSUE TITLE
Include 'type'= 'radar' or 'type'='bar' for numeric indicators

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Urban_Indicators#12]
Related to [this issue](url) we should differentiate in the output between indicators which should be added to the radar chart and indicators which should be added to the bar chart.

Currently, we already have a "category" associated with each indicator, either 'numeric' (default), 'indicators', 'access', or 'heatmap'. As far as I understand, 'numeric' is equivalent to 'indicators' and 'access' is equivalent to 'heatmap'. 
@crisjf would there be any issue with changing the list of options to 'radar', 'bar' and 'access'? Any indicators with the category of 'radar' or 'bar' would be posted to the /indicators end-point (including their category). Also, since the data posted to cityIO can already have a 'category' field (eg. "category": "innovation"}, we should use another name for this in the output. eg. "type": "radar" or "type": "bar".

**Comment by crisjf** [comment]
Perfect!

**Comment by crisjf** [comment]
I clicked the wrong button. 

This sounds good! Those names were placeholders anyways :)

I'll work on it

**Comment by crisjf** [comment]
We will use "indicator_type" instead of "type" as python might get confused.

**Comment by crisjf** [comment]
@doorleyr Let's keep the `indicator_type` either a heatmap or a numeric indicator since it is the only thing the Handler cares about (bars and radar indicators are posted to the same url). There is an extra optional variable called `viz_type` which is set to 'default' by default, but you could either make this 'bar' or 'radar' to make the filtering easier in the front-end.

**Comment by crisjf** [comment]
@doorleyr las thing to close this issue is to make sure the existing indicators work with commit 784f3b12f61fa1f2b83c2bb54153495549f808b0

**Comment by doorleyr** [comment]
Working for all corktown indicators with 13a9999d8a35c906a35ba39efd03fccd140a193f
