### ISSUE TITLE
Scaling of innovation indicators

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Urban_Indicators#18]
The innovation indicator outputs are not in the range (0,1). @crisjf can the outputs be scaled based on the max and min in the training data for example? i.e.
scaled_value= (absolute_value-min)/(max-min)

<img width="929" alt="Screenshot 2020-05-19 at 17 26 51" src="https://user-images.githubusercontent.com/7722116/82352493-fd10df00-99f5-11ea-9d70-e3a58a3c1b61.png">

**Comment by crisjf** [comment]
I forgot about that! hehehe.

**Comment by crisjf** [comment]
Let me know if there's an issue with this!
