### ISSUE TITLE
CityScope categories

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Urban_Indicators#2]
Link between CityScope categories and NAICS codes.

**Comment by LAAP** [comment]
I am waiting for @markus first draft

**Comment by doorleyr** [comment]
@LAAP can we see a draft or something? Just want to make sure we're all on the same page about what needs to be produced.

**Comment by LAAP** [comment]
@doorleyr , Yes. Give us until the end of the week and @Markus we will share an example

**Comment by crisjf** [comment]
@LAAP how are we doing with this?

**Comment by LAAP** [comment]
@crisjf Sorry for the slow motion. I am trying my best

**Comment by LAAP** [comment]
@crisjf, @doorleyr et al., Please, find attached the first draft of the CityScope NAICS categories for Amenities (Housing is not included), related to the categories used in the "old excel version" of the CS Radar Plot:

**CityScope categories .xlsx file:**
[200405_CityScope categories.xlsx](https://github.com/CityScope/CS_Urban_Indicators/files/4435391/200405_CityScope.categories.xlsx)

**Google doc. CityScience Parcel Attributes/CityScope categories:**
https://docs.google.com/spreadsheets/d/1S57LJHtZklmHplF08b3oA3qnd8Hx6DqMUQXvj9wO-oU/edit?usp=sharing

Please, let me know your thoughts

**Comment by crisjf** [comment]
Amazing! Now we can push this to the finish line!
