### ISSUE TITLE
Indicators should return both raw and normalised values and units

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Urban_Indicators#20]
In order to allow a new reporting functionality on the front-end, the indicators should return raw values of indicators and units (where applicable) as well as the value normalised to (0,1).

eg.
{
'name': Average Salary',
'value': 0.6,
'raw_value': 60000,
'units': 'USD'
}

**Comment by doorleyr** [comment]
@crisjf can you check out this commit and make sure it's ok? Also, can you fill in units for your indicators if any?
9ee0ff69419932a0648961b457561f75cd9b9e73

**Comment by crisjf** [comment]
Hey! that looks good. 

For the aggregate indicator, wouldn't you want to also return normalized and non-normalized values?

The only indicator that has units is the RnD one (millions of US dollars per capita). I added them in the last commit (a34eee9305d6da657a8ac785684e8795dd769b0c) and changed the scale of the raw value to a linear scale.

**Comment by doorleyr** [comment]
Thanks! The aggregate indicators are averages of other normalised indicators which may have different units so it wouldn't make sense to give them units.

**Comment by crisjf** [comment]
Makes sense! I think you can go ahead and close this issue.
