### ISSUE TITLE
Indicators should listen to GEOGRIDDATA not GEOGRID

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Urban_Indicators#7]
Since commit c97784bb193594019a8ff28a403261e53237c13f the density and proximity indicators are broken.

This commit was made because the GEOGRIDDATA format was thought to have changed but this is not the case. There should be both a GEOGRID field (geojson that never changes) and a GEOGRIDDATA field (list of descriptive objects which represents the dynamic table state) on cityIO. However, yesterday, the GEOGRIDDATA field was temporarily removed for debugging an issue with the front end. The GEOGRIDDATA is now back and this is what the Handler should be listening to.

**Comment by crisjf** [comment]
This was an easy fix, as the handler class has a keyword argument `GEOGRID_varname` that points to the variable the indicators will listen to.

**Comment by crisjf** [comment]
Ariel  1 hour ago
not sure if relevant, but keep in mind that GEOGRIDDATA can / will disappear at times. In fact, in a new table instance it does not exist until user interaction creates it

Cris  9 minutes ago
Good to know. I won't be an issue though. The Handler python class takes in the variable to listen to as a keyword argument. So if a table posts the data as  THE_COOL_GRID, this can be easily accommodated.
